version: '3.9'
services:
  azuracast-redis:
    image: redis
    container_name: AzuraCast-REDIS
    hostname: azuracast-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /home/umbrel/umbrel/my-configs/azuracast-config/redis:/data
    restart: always

  azuracast-db:
    image: mariadb:11.3-jammy
    container_name: AzuraCast-DB
    hostname: azuracast-db
    environment:
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=azuracastrootpw
      - MYSQL_DATABASE=azuracast
      - MYSQL_USER=azuracastuser
      - MYSQL_PASSWORD=azuracastpw
    volumes:
      - /home/umbrel/umbrel/my-configs/azuracast-config/dbconfig:/var/lib/mysql:rw
    restart: always

  azuracast:
    image: azuracast/azuracast:latest
    container_name: AzuraCast
    hostname: azuracast
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
    ports:
      - 8421:80
      - 8000:8000
      - 8119:8005
      - 8113:8006
      - 8114:8010
      - 8115:8015
      - 8116:8016
      - 8117:8020
    environment:
      - APPLICATION_ENV=production
      - MYSQL_HOST=azuracast-db
      - MYSQL_PORT=3306
      - MYSQL_USER=azuracastuser
      - MYSQL_PASSWORD=azuracastpw
      - MYSQL_DATABASE=azuracast
      - ENABLE_REDIS=true
      - REDIS_HOST=azuracast-redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - TZ=Europe/Madrid
    volumes:
      - /home/umbrel/umbrel/data/storage/azuracast/uploads:/var/azuracast/uploads
      - /home/umbrel/umbrel/data/storage/azuracast/stations:/var/azuracast/stations
      - /home/umbrel/umbrel/my-configs/azuracast-config/shoutcast:/var/azuracast/servers/shoutcast2
      - /home/umbrel/umbrel/my-configs/azuracast-config/stereo:/var/azuracast/servers/stereo_tool
      - /home/umbrel/umbrel/my-configs/azuracast-config/geoip:/var/azuracast/geoip
      - /home/umbrel/umbrel/my-configs/azuracast-config/persist:/var/azuracast/sftpgo/persist
      - /home/umbrel/umbrel/my-configs/azuracast-config/backups:/var/azuracast/backups
      - /home/umbrel/umbrel/my-configs/azuracast-config/acme:/var/azuracast/acme
      - /home/umbrel/umbrel/my-configs/azuracast-config/dbmysql:/var/lib/mysql
    restart: always
    depends_on:
      azuracast-redis:
        condition: service_healthy
      azuracast-db:
        condition: service_started