version: '3.7'

services:
  azurarelay:
    image: azuracast/azurarelay:latest
    container_name: azurarelay
    environment:
      - AZURARELAY_HTTP_PORT=8421
      - AZURARELAY_HTTPS_PORT=443
    ports:
      - "8421:80"
      - "8443:443"
    volumes:
      - /home/umbrel/umbrel/my-configs/azurarelay-config:/var/app/www_tmp/azurarelay.env
      - /home/umbrel/umbrel/my-configs/azurarelay-data:/var/azurarelay
      - /home/umbrel/umbrel/my-configs/azurarelay-db:/var/lib/mysql
      - /home/umbrel/umbrel/my-configs/azurarelay-redis:/data
      - /home/umbrel/umbrel/data/storage/Deemix:/var/azurarelay/music
    restart: always
    depends_on:
      - azurarelay-db
      - azurarelay-redis

  azurarelay-db:
    image: mariadb:11.3-jammy
    container_name: azurarelay-db
    environment:
      - MYSQL_ROOT_PASSWORD=azuracastrootpw
      - MYSQL_DATABASE=azurarelay
      - MYSQL_USER=azurarelayuser
      - MYSQL_PASSWORD=azurarelaypw
    volumes:
      - /home/umbrel/umbrel/my-configs/azurarelay-db:/var/lib/mysql
    restart: always

  azurarelay-redis:
    image: redis
    container_name: azurarelay-redis
    restart: always
    volumes:
      - /home/umbrel/umbrel/my-configs/azurarelay-redis:/data

volumes:
  azurarelay-config:
  azurarelay-data:
  azurarelay-db:
  azurarelay-redis: